version: 2.1
jobs:
  build:
    working_directory: ~/tpm

    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Install rskjs-util
          command: |
                    cd ~/tpm/
                    npm i  
      - run:
          name: Run Tests
          command: npm test
